language: ruby
rvm:
- 2.2.2

before_script:

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
 - gem install jekyll html-proofer
 - JEKYLL_ENV=production jekyll build && htmlproofer ./_site

sudo: false
